#cloud-config
ssh_pwauth: yes
chpasswd:
  list: |
    ubuntu:ubuntu
    root:root
  expire: false

write_files:
  - path: /etc/netplan/50-cloud-init.yaml
    owner: root:root
    permissions: '0644'
    content: |
      network:
        version: 2
        ethernets:
          enp1s0:
              dhcp4: true
              match:
                  macaddress: '52:54:00:01:01:01'
              set-name: enp1s0
          enp2s0:
              dhcp4: false
              match:
                  macaddress: '52:54:00:01:01:02'
              set-name: enp2s0
              addresses:
                - 10.0.0.2/24

package_upgrade: true

packages:
   - jq

runcmd:
  - apt-get install qemu-kvm libvirt-daemon-system libvirt-daemon virtinst bridge-utils libosinfo-bin libguestfs-tools virt-top -y
  - snap install maas-test-db
  - snap install maas --channel=2.9/stable
  - maas init region+rack --maas-url http://10.0.0.2:5240/MAAS --database-uri maas-test-db:///
  - maas createadmin --username admin --password ubuntu --email admin@example.com
  - maas apikey --username admin > ~ubuntu/admin-api-key
  - mkdir -p /var/snap/maas/current/root/.ssh
  - ssh-keygen -q -N '' -f /var/snap/maas/current/root/.ssh/id_rsa

power_state:
  mode: reboot
